// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckModToolsRunning() {
  return window['go']['main']['App']['CheckModToolsRunning']();
}

export function CleanupLocalStorage() {
  return window['go']['main']['App']['CleanupLocalStorage']();
}

export function CleanupTempFiles() {
  return window['go']['main']['App']['CleanupTempFiles']();
}

export function DownloadSkin(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['DownloadSkin'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function FetchChampionJson(arg1) {
  return window['go']['main']['App']['FetchChampionJson'](arg1);
}

export function GetInstalledSkins() {
  return window['go']['main']['App']['GetInstalledSkins']();
}

export function GetModStatus() {
  return window['go']['main']['App']['GetModStatus']();
}

export function GetUserData(arg1) {
  return window['go']['main']['App']['GetUserData'](arg1);
}

export function InstallSkin(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['InstallSkin'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function KillModTools() {
  return window['go']['main']['App']['KillModTools']();
}

export function LoadInstalledSkins() {
  return window['go']['main']['App']['LoadInstalledSkins']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Register(arg1, arg2, arg3) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3);
}

export function RestartModTools() {
  return window['go']['main']['App']['RestartModTools']();
}

export function RunAndWaitModToolCommand(arg1, arg2) {
  return window['go']['main']['App']['RunAndWaitModToolCommand'](arg1, arg2);
}

export function RunModToolCommand(arg1, arg2) {
  return window['go']['main']['App']['RunModToolCommand'](arg1, arg2);
}

export function RunOverlay(arg1) {
  return window['go']['main']['App']['RunOverlay'](arg1);
}

export function SaveInstalledSkins() {
  return window['go']['main']['App']['SaveInstalledSkins']();
}

export function SaveModStatus(arg1) {
  return window['go']['main']['App']['SaveModStatus'](arg1);
}

export function StartOverlay() {
  return window['go']['main']['App']['StartOverlay']();
}

export function StartRunOverlay() {
  return window['go']['main']['App']['StartRunOverlay']();
}

export function StopOverlay() {
  return window['go']['main']['App']['StopOverlay']();
}

export function StopRunOverlay() {
  return window['go']['main']['App']['StopRunOverlay']();
}

export function UninstallMultipleSkins(arg1) {
  return window['go']['main']['App']['UninstallMultipleSkins'](arg1);
}

export function UninstallSkin(arg1) {
  return window['go']['main']['App']['UninstallSkin'](arg1);
}

export function UpdateUserData(arg1, arg2) {
  return window['go']['main']['App']['UpdateUserData'](arg1, arg2);
}
