// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanupLocalStorage():Promise<Record<string, any>>;

export function CleanupTempFiles():Promise<void>;

export function DownloadSkin(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string):Promise<Record<string, any>>;

export function FetchChampionJson(arg1:string):Promise<Record<string, any>>;

export function GetInstalledSkins():Promise<Array<Record<string, any>>>;

export function GetModStatus():Promise<any>;

export function GetUserData(arg1:string):Promise<Record<string, any>>;

export function InstallSkin(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<Record<string, any>>;

export function KillModTools():Promise<boolean>;

export function LoadInstalledSkins():Promise<void>;

export function Login(arg1:string,arg2:string):Promise<Record<string, any>>;

export function Register(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function RestartModTools():Promise<boolean>;

export function RunAndWaitModToolCommand(arg1:string,arg2:Array<string>):Promise<Record<string, any>>;

export function RunModToolCommand(arg1:string,arg2:Array<string>):Promise<Record<string, any>>;

export function RunOverlay(arg1:Array<string>):Promise<Record<string, any>>;

export function SaveInstalledSkins():Promise<void>;

export function SaveModStatus(arg1:Record<string, any>):Promise<Record<string, any>>;

export function StartOverlay():Promise<Record<string, any>>;

export function StartRunOverlay():Promise<Record<string, any>>;

export function StopOverlay():Promise<Record<string, any>>;

export function StopRunOverlay():Promise<Record<string, any>>;

export function UninstallMultipleSkins(arg1:Array<string>):Promise<Record<string, any>>;

export function UninstallSkin(arg1:string):Promise<Record<string, any>>;

export function UpdateUserData(arg1:string,arg2:Record<string, any>):Promise<void>;
